services:
  - type: web
    name: tracker
    runtime: node
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm start --prefix backend
    envVars:
      - key: VITE_GOOGLE_APPS_SCRIPT_URL
        sync: false
